networks:
  polaris: {}
  database:
    external: true
    name: database_database

services:
  polaris-server:
    image: polarismesh/polaris-server:v1.18.1
    restart: always
    volumes:
      - ./server/polaris-server.yaml:/root/conf/polaris-server.yaml
    expose: # 用于北极星集群内部访问
      - 8090    # api-http
      - 8091    # service-grpc
      - 8093    # config-grpc
      - 8761    # service-eureka
      - 8848    # nacos-http port
      - 9848    # nacos-grpc port
      - 15010   # xds-v3
    ports: # 用于其他服务访问北极星
      - "8090:8090" # api-http
      - "8091:8091" # service-grpc
      - "8093:8093" # config-grpc
      - "8761:8761" # service-eureka
      - "8848:8848" # nacos-http port
      - "9848:9848" # nacos-grpc port
      - "15010:15010" # xds-v3
    networks:
      - polaris
      - database

  polaris-console:
    image: polarismesh/polaris-console:v1.15.0
    restart: always
    volumes:
      - ./console/polaris-console.yaml:/root/polaris-console.yaml
    ports:
      - "8080:8080"
    networks:
      - polaris
      - database
    depends_on:
      - polaris-server

  polaris-limiter:
    image: polarismesh/polaris-limiter:v1.0.4
    restart: always
    environment:
      - MY_ID=1
    volumes:
      - ./limiter/polaris-limiter.yaml:/root/polaris-limiter.yaml
    expose: # 用于北极星集群内部访问
      - 8100    # service-http
      - 8101    # service-grpc
    ports:
      - "8100:8100"
      - "8101:8101"
    networks:
      - polaris
      - database
    depends_on:
      - polaris-server
